### ISSUE TITLE
Sensor is created and HACS add-on is installed, but card is not visible

### ISSUE THREAD

**Issue by riddledaxis** [pasleto/lovelace-iphone-xs-card#1]
Hi,

I installed your add-on via HACS, followed your example code and created a sensor called pj_iphone_x.

When I create a manual card in the frontend with the following config, it looks like a card is there but nothing is visible.
```
type: 'custom:iphone-xs-card'
entity: sensor.pj_iphone_x
```
![iphone card not visible](https://user-images.githubusercontent.com/47009467/97207996-8b15a080-17b2-11eb-9bc8-6f1c946cbc15.png)

I also created a new tab in the frontend in panel mode and again it looks like the card is there but nothing is visible.
![iphone card in panel mode](https://user-images.githubusercontent.com/47009467/97208002-8bae3700-17b2-11eb-9860-bdfaf4e4b8ea.png)

Please can you advise what I am doing wrong?

Thank you

**Comment by pasleto** [comment]
Hi, can you provide your content of downloaded hacs folder with lovelace-iphone-xs-card? Did you try to reload cache in your browser? Which browser do you use? Did you linked this card to your lovelace/configuration file?

**Comment by riddledaxis** [comment]
Hi,

This is my HACS folder contents, I reinstalled the add-on to be sure everything was ok
![card_folder](https://user-images.githubusercontent.com/47009467/97212418-4ee53e80-17b8-11eb-8833-6c7daa1aa793.png)

Yes, I reloaded the cache when I installed and then re-installed it and I also ctl+F5, to force reload of the page/card.

I am using the latest MS Edge browser as a web app (v84.0.522.52) and I have also tried it in Firefox (v81.0.2)

I am running HassOS 4.15 and HA 0.116.4 

HACS added it to resources 
![lovelace_resources](https://user-images.githubusercontent.com/47009467/97213254-46413800-17b9-11eb-93f0-c3a61c627259.png)

**Comment by pasleto** [comment]
I dont see anythign wrong here, i have not tested it on HA 0.116.x yet, but it should be working i guess, and it´s definitely working in MS Edge and Firefox. Anything in logs? Try access the files trough web browser ->
http://your-ha-ip:8123/hacsfiles/lovelace-iphone-xs-card/lovelace-iphone-xs-card.js
http://your-ha-ip:8123/hacsfiles/lovelace-iphone-xs-card/iphone_xs.png

**Comment by riddledaxis** [comment]
I browsed both files in MS Edge and Firefox and they both display ok:
<img src="https://user-images.githubusercontent.com/47009467/97225489-a2f91e80-17ca-11eb-9785-8173cec38316.png" width= "300" height="300">
<img src="https://user-images.githubusercontent.com/47009467/97225490-a391b500-17ca-11eb-8c9b-5b71cd64b03d.png" width="350" height="350">

The only thing I could find in the logs was the reinstallation
```
2020-10-26 18:15:06 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Registration completed
2020-10-26 18:15:15 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Running pre installation steps
2020-10-26 18:15:15 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Pre installation steps completed
2020-10-26 18:15:15 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Running installation steps
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of wifi.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of sim_1.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of device_type.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of sim_2.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of plug.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of lovelace-iphone-xs-card.js completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of iphone_xs.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Download of battery.png completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Installation steps completed
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Running post installation steps
2020-10-26 18:15:17 INFO (MainThread) [custom_components.hacs.repository.plugin.pasleto.lovelace-iphone-xs-card] Post installation steps completed
```
The only other thing I can think of is that I am using https inside and outside my network. Not sure if that would cause an issue even though the files do display?

**Comment by pasleto** [comment]
Can you try load the card without entity passed in? It should display error message about missing senso.? 
What is showing in place where the card should be placed? 
Can you check code with developer tools?
Https shouldn´t be a problem, when files are loaded inside the web through url.

Maybe remove your HA url out of the pictures ;)

**Comment by riddledaxis** [comment]
If I remove the entity I get this error
<img src="https://user-images.githubusercontent.com/47009467/97225873-1e5ad000-17cb-11eb-81b9-0c91d2756b0c.png">
If I configure the card it doesn't display anything there is nothing where the card should be and if I edit that view I get an edit option for the card as below. It is the same the system light or dark theme.
![with_entity_1](https://user-images.githubusercontent.com/47009467/97226171-890c0b80-17cb-11eb-8066-9d941169a6d5.png)

The sensor is working and displays the relevant info in developer tools

<img src="https://user-images.githubusercontent.com/47009467/97227098-e6548c80-17cc-11eb-81ad-7b1db27b0f5b.png" width="350" height="400">

Thanks for the heads up about the URL. now removed ;)

**Comment by pasleto** [comment]
Could you possibly inspect the place where the card should be with browser developer tools (F12)?

**Comment by riddledaxis** [comment]
Where the card should be, it is blank with no data from the sensor

<img src="https://user-images.githubusercontent.com/47009467/97303076-d3d06680-1851-11eb-83bb-c3624cfa6b88.png" width="650" height="350">

**Comment by pasleto** [comment]
The card itself is present, but is empty, weird. I did not upgrade to 0.116 yet, i will try to do it today to eliminate HA version changes. 
What you can try now is:
- remove hacs card
- download the card content from github and place it in "www/lovelace-iphone-xs-card" folder 
- link this folder to lovelace resources (local/lovelace-iphone-xs-card) 
- restart HA
- clear cache in browser or try anonymous window

**Comment by riddledaxis** [comment]
I removed the integration and downloaded the card content as per your above instructions.

I added the lovelace resource and restarted HA, and then logged in through an InPrivate window but the card still didn't display.

![add-on loaded](https://user-images.githubusercontent.com/47009467/97351775-2299f280-188a-11eb-8e4c-8058cf57f44b.png)

I then went back to the webpage inspector, and as you can see from the screenshot below the lovelace-iphone-xs-card.js was still referencing hacsfiles and not local. So I replaced all the hacsfiles references with local, saved the file, logged out of the InPrivate window restarted HA, logged back in and the card still didn't display.

![hacsfiles](https://user-images.githubusercontent.com/47009467/97351745-14e46d00-188a-11eb-9cf1-202dc4886022.png)

I inspected the page again and as you can see from the bottom of the screenshot below, it is now referencing local and not hacsfiles for the images. Also, as you can see the sensor data is being pulled into the card but it is still not being displayed for some reason??

![local](https://user-images.githubusercontent.com/47009467/97351714-07c77e00-188a-11eb-8eb7-a61f7096dcc7.png)

**Comment by pasleto** [comment]
I checked HA 0.116 breaking changes, it seems to be the trouble maker here ...

![image](https://user-images.githubusercontent.com/43222981/97359558-3733b600-189d-11eb-93ca-f3506d3cf777.png)

I will try to check solution as soon as possible

**Comment by riddledaxis** [comment]
Oops, to be fair I didn't think of that

0.117 is due out at some point tomorrow, that might affect this as well?

Thanks for your help, I'll wait to hear back

**Comment by pasleto** [comment]
I didn´t think of that either, but to be fair a didn´t have time to update from 0.115.6 so i didn´t check breaking changes. But when i saw hui-masonry-view in your screenshot I knew that something has changed :D

I think that it will be pretty easy to fix, but i will have to fix all of my cards :/

**Comment by pasleto** [comment]
This card should be fixed and working now on HA 0.116.x  :)

**Comment by riddledaxis** [comment]
Thank you for fixing the card, all working now

![working_card](https://user-images.githubusercontent.com/47009467/97434884-97673e00-1917-11eb-8487-61cf8d64a5d2.png)

Thank you for the quick turnaround :)

**Comment by riddledaxis** [comment]
One last question

In the sensor config, I added a variable called ssid. 

What would I need to change in the card config so that instead of showing Wi-Fi On it showed the ssid?

**Comment by pasleto** [comment]
I have added  this feature, feel free to update your card :) 

It will only work if you can track your wifi status. If your wifi is ON and connected to some SSID it will display the SSID name, if is disconnected but ON it will show ON, if wifi is dissabled => OFF.

**Comment by riddledaxis** [comment]
Looks great

![show ssid](https://user-images.githubusercontent.com/47009467/97441663-df3e9300-1920-11eb-80b2-1939a7a5f33c.png)

Thank you

**Comment by pasleto** [comment]
Thanks, currently working on animation for charging state, should be out soon :)
